// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO73dofnCy8UommtMA97FPyfVRnUCFrbw',
    appId: '1:954922733001:web:b6902a359fb20fe6486c18',
    messagingSenderId: '954922733001',
    projectId: 'flutter-a4f8e',
    authDomain: 'flutter-a4f8e.firebaseapp.com',
    storageBucket: 'flutter-a4f8e.firebasestorage.app',
    measurementId: 'G-0L74MF8HRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC49vPnYWNWc_MmphttRuTyMRIqdh8DEeQ',
    appId: '1:954922733001:android:e93ccf7674210d94486c18',
    messagingSenderId: '954922733001',
    projectId: 'flutter-a4f8e',
    storageBucket: 'flutter-a4f8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClcsIHtI6HGy09f1wPqTWsSIMYevf2hS0',
    appId: '1:954922733001:ios:fc85210553f7bf2f486c18',
    messagingSenderId: '954922733001',
    projectId: 'flutter-a4f8e',
    storageBucket: 'flutter-a4f8e.firebasestorage.app',
    iosBundleId: 'com.cipher.sifr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClcsIHtI6HGy09f1wPqTWsSIMYevf2hS0',
    appId: '1:954922733001:ios:1c114a881f825fcb486c18',
    messagingSenderId: '954922733001',
    projectId: 'flutter-a4f8e',
    storageBucket: 'flutter-a4f8e.firebasestorage.app',
    iosBundleId: 'com.example.cipher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO73dofnCy8UommtMA97FPyfVRnUCFrbw',
    appId: '1:954922733001:web:2ac15418f1a528d4486c18',
    messagingSenderId: '954922733001',
    projectId: 'flutter-a4f8e',
    authDomain: 'flutter-a4f8e.firebaseapp.com',
    storageBucket: 'flutter-a4f8e.firebasestorage.app',
    measurementId: 'G-7M6SMYPZT7',
  );
}
